package com.exchange.model;

import java.util.Objects;

/**
 * Represents an open position in an individual equity instrument within an investment portfolio.
 *
 * @author Mridul Gupta
 * @version 1.0
 * @since 1.0
 */
public class Holding {

    private final String symbol;
    private int quantity;
    private double averageCostBasis;

    /**
     * Constructs a new Holding with an initial lot of shares.
     *
     * @param symbol the equity ticker identifier
     * @param initialQuantity the starting number of shares purchased
     * @param purchasePrice the execution price per share
     */
    public Holding(String symbol, int initialQuantity, double purchasePrice) {
        if (symbol == null || symbol.trim().isEmpty()) {
            throw new IllegalArgumentException("Stock symbol cannot be empty.");
        }
        if (initialQuantity < 0) {
            throw new IllegalArgumentException("Holding quantity cannot be negative.");
        }
        if (purchasePrice < 0) {
            throw new IllegalArgumentException("Purchase price cannot be negative.");
        }
        this.symbol = symbol.trim().toUpperCase();
        this.quantity = initialQuantity;
        this.averageCostBasis = purchasePrice;
    }

    /**
     * Incorporates an additional acquisition of shares into this position, recalculating the
     * weighted-average cost basis.
     *
     * @param addedQuantity the number of newly purchased shares
     * @param unitPrice the execution price paid per newly acquired share
     */
    public synchronized void addShares(int addedQuantity, double unitPrice) {
        if (addedQuantity <= 0) {
            throw new IllegalArgumentException("Added shares quantity must be strictly positive.");
        }
        if (unitPrice < 0) {
            throw new IllegalArgumentException("Unit price cannot be negative.");
        }
        double totalCostBefore = this.quantity * this.averageCostBasis;
        double newCost = addedQuantity * unitPrice;
        this.quantity += addedQuantity;
        this.averageCostBasis = (totalCostBefore + newCost) / this.quantity;
    }

    /**
     * Liquidates a specified quantity of shares from this holding and calculates the realized
     * gain or loss on the sold lot.
     *
     * @param sharesToSell the number of shares to liquidate
     * @param executionPrice the market price at which shares are sold
     * @return the net realized profit or loss generated by this transaction
     */
    public synchronized double removeShares(int sharesToSell, double executionPrice) {
        if (sharesToSell <= 0) {
            throw new IllegalArgumentException("Shares to sell must be strictly positive.");
        }
        if (sharesToSell > this.quantity) {
            throw new IllegalArgumentException("Cannot sell more shares than currently owned.");
        }
        double realizedGainLoss = (executionPrice - this.averageCostBasis) * sharesToSell;
        this.quantity -= sharesToSell;
        // If all shares sold, reset cost basis to zero
        if (this.quantity == 0) {
            this.averageCostBasis = 0.0;
        }
        return realizedGainLoss;
    }

    /**
     * Calculates the total current market value of this position given the prevailing spot price.
     *
     * @param currentMarketPrice the live price per share from the market
     * @return the total gross valuation of the holding
     */
    public synchronized double getMarketValue(double currentMarketPrice) {
        return this.quantity * currentMarketPrice;
    }

    /**
     * Calculates the total cost invested into this position (book value).
     *
     * @return the total book value invested in this holding
     */
    public synchronized double getTotalCost() {
        return this.quantity * this.averageCostBasis;
    }

    /**
     * Calculates the total unrealized (paper) profit or loss for this position.
     *
     * @param currentMarketPrice the live spot price of the stock
     * @return the unrealized gain (positive) or loss (negative)
     */
    public synchronized double getUnrealizedProfitLoss(double currentMarketPrice) {
        return (currentMarketPrice - this.averageCostBasis) * this.quantity;
    }

    /**
     * Calculates the unrealized return on investment (ROI) percentage.
     *
     * @param currentMarketPrice the live spot price of the stock
     * @return the return percentage relative to the cost basis
     */
    public synchronized double getUnrealizedRoiPercent(double currentMarketPrice) {
        if (this.averageCostBasis <= 0 || this.quantity == 0) {
            return 0.0;
        }
        return ((currentMarketPrice - this.averageCostBasis) / this.averageCostBasis) * 100.0;
    }

    /**
     * Retrieves the equity ticker symbol.
     *
     * @return the ticker symbol
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Retrieves the number of shares currently held.
     *
     * @return the active share quantity
     */
    public synchronized int getQuantity() {
        return quantity;
    }

    /**
     * Retrieves the weighted average purchase cost basis per share.
     *
     * @return the average cost basis
     */
    public synchronized double getAverageCostBasis() {
        return averageCostBasis;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Holding holding)) return false;
        return Objects.equals(symbol, holding.symbol);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol);
    }

    @Override
    public String toString() {
        return String.format("%-6s | Qty: %-5d | Avg Cost: $%,.2f | Total Cost: $%,.2f",
                symbol, quantity, averageCostBasis, getTotalCost());
    }
}
