package com.exchange.model;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Manages an investor's active equity holdings, transaction audit history, and financial metrics.
 *
 * @author Mridul Gupta
 * @version 1.0
 * @since 1.0
 */
public class Portfolio {

    private final Map<String, Holding> holdings;
    private final List<Transaction> transactionHistory;
    private double cumulativeRealizedProfitLoss;

    /**
     * Constructs a new, empty Portfolio.
     */
    public Portfolio() {
        this.holdings = new ConcurrentHashMap<>();
        this.transactionHistory = Collections.synchronizedList(new ArrayList<>());
        this.cumulativeRealizedProfitLoss = 0.0;
    }

    /**
     * Records a new acquisition of shares, updating existing positions or opening new ones.
     *
     * @param symbol the equity ticker symbol
     * @param quantity the number of shares acquired
     * @param purchasePrice the execution price per share
     */
    public synchronized void addHolding(String symbol, int quantity, double purchasePrice) {
        if (symbol == null || symbol.trim().isEmpty()) {
            throw new IllegalArgumentException("Symbol cannot be empty.");
        }
        if (quantity <= 0 || purchasePrice <= 0) {
            throw new IllegalArgumentException("Quantity and price must be strictly positive.");
        }
        String key = symbol.trim().toUpperCase();
        Holding holding = holdings.get(key);
        if (holding == null) {
            holdings.put(key, new Holding(key, quantity, purchasePrice));
        } else {
            holding.addShares(quantity, purchasePrice);
        }
    }

    /**
     * Liquidates shares from an existing position, reducing share count and realizing gains/losses.
     *
     * @param symbol the equity ticker symbol
     * @param quantity the number of shares to sell
     * @param sellPrice the prevailing execution price
     * @return the realized profit or loss generated by this liquidation
     * @throws IllegalArgumentException if the position does not exist or has insufficient shares
     */
    public synchronized double removeHolding(String symbol, int quantity, double sellPrice) {
        if (symbol == null || symbol.trim().isEmpty()) {
            throw new IllegalArgumentException("Symbol cannot be empty.");
        }
        String key = symbol.trim().toUpperCase();
        Holding holding = holdings.get(key);
        if (holding == null || holding.getQuantity() < quantity) {
            throw new IllegalArgumentException("Insufficient holdings for " + symbol);
        }
        double realized = holding.removeShares(quantity, sellPrice);
        this.cumulativeRealizedProfitLoss += realized;
        if (holding.getQuantity() == 0) {
            holdings.remove(key);
        }
        return realized;
    }

    /**
     * Appends an executed trade record to the permanent transaction ledger.
     *
     * @param transaction the completed transaction record
     */
    public void recordTransaction(Transaction transaction) {
        if (transaction != null) {
            transactionHistory.add(transaction);
        }
    }

    /**
     * Calculates the gross market valuation of all currently held stocks.
     *
     * @param stockLookup functional provider or map supplying current stock prices
     * @return total market valuation of active holdings
     */
    public synchronized double getMarketValue(Map<String, Double> stockLookup) {
        double total = 0.0;
        for (Holding h : holdings.values()) {
            Double price = stockLookup.get(h.getSymbol());
            if (price != null && price > 0) {
                total += h.getMarketValue(price);
            }
        }
        return Math.round(total * 100.0) / 100.0;
    }

    /**
     * Calculates the total book cost invested in current open holdings.
     *
     * @return aggregate cost basis of open positions
     */
    public synchronized double getTotalInvestedCost() {
        double total = 0.0;
        for (Holding h : holdings.values()) {
            total += h.getTotalCost();
        }
        return Math.round(total * 100.0) / 100.0;
    }

    /**
     * Calculates total unrealized (paper) gains or losses on all open positions.
     *
     * @param stockLookup map containing live stock prices
     * @return net unrealized gain/loss
     */
    public synchronized double getUnrealizedProfitLoss(Map<String, Double> stockLookup) {
        double total = 0.0;
        for (Holding h : holdings.values()) {
            Double price = stockLookup.get(h.getSymbol());
            if (price != null) {
                total += h.getUnrealizedProfitLoss(price);
            }
        }
        return Math.round(total * 100.0) / 100.0;
    }

    /**
     * Retrieves the cumulative realized profit or loss from completed sales.
     *
     * @return total realized profit or loss
     */
    public synchronized double getCumulativeRealizedProfitLoss() {
        return Math.round(cumulativeRealizedProfitLoss * 100.0) / 100.0;
    }

    /**
     * Sets the cumulative realized profit or loss, typically during state restoration.
     *
     * @param amount the loaded cumulative realized gain/loss
     */
    public synchronized void setCumulativeRealizedProfitLoss(double amount) {
        this.cumulativeRealizedProfitLoss = amount;
    }

    /**
     * Retrieves an individual holding by stock symbol if present.
     *
     * @param symbol the equity ticker symbol
     * @return the active Holding, or {@code null} if not currently owned
     */
    public Holding getHolding(String symbol) {
        if (symbol == null) return null;
        return holdings.get(symbol.trim().toUpperCase());
    }

    /**
     * Retrieves an unmodifiable view of all active equity holdings.
     *
     * @return map of symbols to active holdings
     */
    public Map<String, Holding> getHoldings() {
        return Collections.unmodifiableMap(holdings);
    }

    /**
     * Retrieves an unmodifiable copy of the completed transaction ledger.
     *
     * @return list of chronological transactions
     */
    public List<Transaction> getTransactionHistory() {
        return Collections.unmodifiableList(new ArrayList<>(transactionHistory));
    }

    /**
     * Checks if the portfolio holds shares in any equity.
     *
     * @return {@code true} if at least one stock is owned, otherwise {@code false}
     */
    public boolean hasHoldings() {
        return !holdings.isEmpty();
    }
}
